jobs:
  docker-and-npm-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérification du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installer Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Installer Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # 4. Démarrage des services avec Docker Compose
      - name: Start Docker Compose services
        run: |
          docker-compose -f compose.yml up -d
        env:
          POSTGRES_USER: manamon
          POSTGRES_PASSWORD: manamon
          POSTGRES_DB: manamon

      # 5. Vérification des services Docker
      - name: Verify Docker services are running
        run: docker-compose ps

      # 6. Installation des dépendances NPM
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'

      - name: Install dependencies
        working-directory: ./api
        run: npm install

      # 7. Attente que PostgreSQL soit prêt
      - name: Wait for PostgreSQL to be ready
        run: |
          until docker exec manamon-club-db pg_isready -U manamon -d manamon; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      # 8. Appliquer les migrations Prisma
      - name: Apply Prisma migrations
        working-directory: ./api
        run: npx prisma migrate deploy

      # 9. Peuplement de la base de données
      - name: Populate database
        working-directory: ./api
        run: npm run populate

      # 10. Lancer les tests avec Jest
      - name: Run tests
        working-directory: ./api
        run: npm test

      # 11. Nettoyage des conteneurs Docker
      - name: Tear down Docker Compose
        if: always()
        run: docker-compose -f compose.yml down
